# Generated by Django 5.1.2 on 2024-11-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='会社名')),
                ('image', models.ImageField(default='images/default.png', upload_to='images/', verbose_name='会社画像')),
                ('job_description', models.TextField(verbose_name='仕事内容')),
                ('strengths', models.CharField(blank=True, default='特になし', max_length=255, null=True, verbose_name='強み')),
                ('location', models.CharField(default='未定', max_length=255, verbose_name='勤務地')),
                ('working_hours', models.CharField(blank=True, default='不明', max_length=255, null=True, verbose_name='勤務時間')),
                ('salary', models.CharField(blank=True, default='要相談', max_length=255, null=True, verbose_name='給料')),
                ('benefits', models.CharField(blank=True, default='特になし', max_length=255, null=True, verbose_name='福利厚生')),
                ('annual_holidays', models.CharField(blank=True, default='未定', max_length=255, null=True, verbose_name='年間休日')),
                ('hires', models.CharField(blank=True, default='不明', max_length=255, null=True, verbose_name='採用人数')),
                ('selection_process', models.TextField(blank=True, default='選考フローは未定', null=True, verbose_name='選考フロー')),
                ('notes', models.TextField(blank=True, default='特記事項なし', null=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
